version: '3.5'
 
services:
  database:
    container_name: database_container
    image: postgres:12.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Welcome01}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    # expose:
    #   - "5432"
    ports:
      - "5431:5432"
    networks:
      - dbnetwork
    restart: unless-stopped
  
  # migrate:
  #   container_name: migrate_container
  #   image: migrate/migrate
  #   depends_on: 
  #     - postgres
  #   volumes: 
  #     - /database/migrations:/migrations
  #   networks: 
  #     - dbnetwork
  #   command: ["-path", "/migrations", "-database", "postgres://postgres:Welcome01@postgres_container/marketdb?sslmode=disable", "up", "3"]
  #   links: 
  #     - postgres
   
  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4:4.16
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - pgadmin:/root/.pgadmin
  #   # expose:
  #   #   - "80"
  #   ports:
  #     - "${PGADMIN_PORT:-5054}:80"
  #   links: 
  #     - postgres
  #   networks:
  #     - dbnetwork
  #     - marketnetwork
  #   restart: unless-stopped


  golang:
    container_name: golang_container
    build: ./backend/golang
    env_file: 
      - ./backend/golang/.env
    volumes: 
      - ./backend/golang:/usr/src/app/
    # expose:
    #   - "5053"
    ports:
      - "5053:5053"
    depends_on: 
      - database
    networks: 
      - dbnetwork
      - marketnetwork
    restart: on-failure

  # frontend-angular:
  #   container_name: front-public_container
  #   build: ./frontend-angular
  #   ports: 
  #     - "4200:80"
  #   depends_on: 
  #     - golang
  #   networks: 
  #     - dbnetwork
  # nginx:
  #   build: "./nginx"
  #   restart: always
  #   expose:
  #     - "80"
  #   ports:
  #     - "5055:80"
  #     - "443:443"
  #   depends_on: 
  #     - golang
  #   networks: 
  #     - marketnetwork
      
networks:
  marketnetwork:
    driver: bridge
  dbnetwork:
 
volumes:
    postgres:
    pgadmin: