version: '3.5'
 
services:

  postgres:
    container_name: postgres_container
    image: postgres:12.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Welcome01}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    expose:
      - "5432"
    # ports:
    #   - "5432:5432"
    networks:
      - dbnetwork
    restart: unless-stopped
   
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:4.16
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    # expose:
    #   - "80"
    ports:
      - "${PGADMIN_PORT:-5054}:80"
    networks:
      - dbnetwork
      - marketnetwork
    restart: unless-stopped
    depends_on: 
      - postgres

  golang:
    container_name: golang_container
    build: ./backend
    env_file: 
      - ./backend/.env
    volumes: 
      - ./backend:/usr/src/app/
    expose:
      - "5053"
    # ports:
    #   - "5053:5053"
    depends_on: 
      - postgres
    networks: 
      - dbnetwork
      - marketnetwork
    restart: on-failure

  nginx:
    build: "./nginx"
    restart: always
    expose:
      - "80"
    ports:
      - "5055:80"
      - "443:443"
    depends_on: 
      - golang
    networks: 
      - marketnetwork
      
networks:
  marketnetwork:
    driver: bridge
  dbnetwork:
 
volumes:
    postgres:
    pgadmin: