version: '3.5'
 
services:
  postgres:
    container_name: market_postgres_container
    image: postgres:12.1
    env_file: 
      - ./database/postgres/.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5431:5432"
    networks:
      - dbnetwork
    restart: unless-stopped

  redis:
    container_name: market_redis_container
    image: redis:5.0
    ports:
      - "6379:6379"
    networks:
      - dbnetwork
  # migrate:
  #   container_name: migrate_container
  #   image: migrate/migrate
  #   depends_on: 
  #     - postgres
  #   volumes: 
  #     - /database/migrations:/migrations
  #   networks: 
  #     - dbnetwork
  #   command: ["-path", "/migrations", "-database", "postgres://postgres:Welcome01@postgres_container/marketdb?sslmode=disable", "up", "3"]
  #   links: 
  #     - postgres
   
  # pgadmin:
  #   container_name: market_pgadmin_container
  #   image: dpage/pgadmin4:4.16
  #   env_file: 
  #     - ./webservers/pgadmin/.env
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - pgadmin:/root/.pgadmin
  #   ports:
  #     - "5050:80"
  #   links: 
  #     - postgres
  #   networks:
  #     - dbnetwork
  #     - marketnetwork
  #   restart: unless-stopped


  golang:
    container_name: market_golang_container
    build: ./backend/golang
    env_file: 
      - ./backend/golang/.env
    volumes: 
      - ./backend/golang:/usr/src/app/
    ports:
      - "5053:5053"
    depends_on: 
      - postgres
      - redis
    networks: 
      - dbnetwork
      - marketnetwork
    restart: on-failure

  frontend-angular:
    container_name: angular_container
    build: ./frontend/frontend-angular
    ports: 
      - "4200:80"
    depends_on: 
      - golang
    networks: 
      - dbnetwork
  # nginx:
  #   build: "./nginx"
  #   restart: always
  #   expose:
  #     - "80"
  #   ports:
  #     - "5055:80"
  #     - "443:443"
  #   depends_on: 
  #     - golang
  #   networks: 
  #     - marketnetwork
      
networks:
  marketnetwork:
    driver: bridge
  dbnetwork:
 
volumes:
    postgres:
    pgadmin: