version: '3.5'
 
services:
  golang:
    container_name: golang_container
    build: .
    env_file: 
      - backend/.env
    volumes: 
      - backend:/usr/src/app/
    ports:
      - "5500:5500"
    depends_on: 
      - postgres
    networks: 
      - marketnetwork
    restart: on-failure

  postgres:
    container_name: postgres_container
    image: postgres:12.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Welcome01}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - marketnetwork
    restart: unless-stopped
   
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:4.16
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - marketnetwork
    restart: unless-stopped
 
networks:
  postgres:
    driver: bridge
 
volumes:
    postgres:
    pgadmin: