name: OnlineMarket

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
#     - name: Test
#       run: cd backend/golang
#       run: go test ./...
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Compose build
        run: docker-compose build -t
      - name: Tags
        run: |
          docker tag online-market ${{ secrets.DOCKER_USER }}/online-market:${{ github.sha }}
          docker tag online-market ${{ secrets.DOCKER_USER }}/online-market:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/online-market:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/online-market:latest
